config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/:name", to: "topics#show", as: :topic, constraints: { name: /.+/ }
  # get "/request", to: "pages#request"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def request
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topic = Topic.find_by(name: params[:name])

    if @topic.nil?
      # Handle the case when the topic is not found
      redirect_to root_path, alert: "Topic not found"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fromrubyto</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/about.html.erb
about page

app/views/pages/contact.html.erb
<div class="container my-4 py-4">
  <h1 class="mb-4">Reach me</h1>
    <div class="social-links px-3">
      <a href="https://github.com/jaimiblank" class="social-icon" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-github"></i></a>
      <a href="https://www.linkedin.com/in/jaimilklein" class="social-icon" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a>
      <a href="mailto:jk@jaimiklein.com" class="social-icon" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-envelope"></i></a>
    </div>
</div>

app/views/pages/home.html.erb
<div class="home-container">
  <header>
    <h1>From Ruby to</h1>
    <h2>Where do you want to go?</h2>
  </header>

  <div class="card-container">
    <% Topic.all.first(10).each do |topic| %>
      <%= link_to topic_path(name: topic.name), class: "card" do %>
        <div>
          <h3><%= topic.name %></h3>
          <p><%= topic.subtitle %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/projects.html.erb
projects page

app/views/pages/request.html.erb
make a request!

app/views/pages/skills.html.erb
skills page

app/views/topics/show.html.erb
<div class="container">
  <h1><%= @topic.name %></h1>
  <h2><%= @topic.subtitle %></h2>
  <div class="content">
    <% if @topic.content.present? %>
      <%= @topic.content %>
    <% else %>
      <p>Content goes here</p>
    <% end %>
  </div>
</div>